SELECT tenhang, tennsx
FROM HANGHOA, NHASANXUAT
WHERE HANGHOA.mansx = NHASANXUAT.mansx;

SELECT tenhang, tennsx
FROM HANGHOA, NHASANXUAT
WHERE HANGHOA.mansx = NHASANXUAT.mansx;

SELECT mahd, tenkh
FROM HOADON, KHACHHANG
WHERE HOADON.makh = KHACHHANG.makh;